### ISSUE TITLE
mobile first?

### ISSUE THREAD

**Issue by hasansaad1** [FACN3/mashrou_ghazal#40]
the website is not a very responsive one, also you should work on the mobile version a bit to make it easier to be used.
![image](https://user-images.githubusercontent.com/30749442/33163697-5ac0368a-d038-11e7-8706-5a0b609f5bcd.png)
![image](https://user-images.githubusercontent.com/30749442/33163721-706a8080-d038-11e7-8a17-ef1c04a3d037.png)

:smile:

**Comment by Amirk390** [comment]
@hasansaad1 Thanks :smile: 
Its fixed now
