### ISSUE TITLE
Where are you hosting?

### ISSUE THREAD

**Issue by matthewdking** [FACN3/mashrou_ghazal#42]
It looks from the url you have supplied in the repo that you are hosting on heroku
```
http://immense-ravine-82923.herokuapp.com/
```
In your package.json you have installed `@google-cloud/nodejs-repo-tools` which is for a google cloud service. Is this being used still seeing as you have heroku? If it is unused it should be uninstalled and the app.yaml file removed as well.

**Comment by ghassanmas** [comment]
We have deployed on both. 
https://welvon-api.appspot.com

**Comment by Amirk390** [comment]
@matthewdking
