### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by matthewdking** [FACN3/mashrou_ghazal#53]
Love the fact you are including a diagram of the architecture :star2: 

The relationships between server, handlers and autocomplete in the diagram seems a bit weird as all the data/logic is going back and forth between all of them. My understanding of the logic for this project would be something like:
```
server <--> router <--> handlers <--> autocomplete logic
```

**Comment by Amirk390** [comment]
I will fix it 
Thanks :smiley:

**Comment by Amirk390** [comment]
Fixed @matthewdking :+1:
