### ISSUE TITLE
functionality of searching

### ISSUE THREAD

**Issue by hasansaad1** [FACN3/mashrou_ghazal#55]
there is a bit of a functionality problem < because that your data is just one word its passing but because your always searching for the the last word , if I searched for one term of two words that you have it in the data as one term of two words it wouldn't find it because it is going to look for a term that starts with the second word in your search term.

**Comment by hoslack** [comment]
I am sure you had a clear understanding of the requirements for the project. We are supposed to help you auto-complete a single word. @hasansaad1
